"""empty message

Revision ID: 5061a9860b85
Revises: 805eece8945f
Create Date: 2023-10-26 17:23:00.147845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5061a9860b85'
down_revision = '805eece8945f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email2', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['email2'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email2')

    # ### end Alembic commands ###
